/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import PaperAccount.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Owner
 */
public class AccountPanel extends javax.swing.JPanel {

    private AccountDetails account; 
    private TradeHistory tradeHistory;
    
    private DefaultListModel<String> startDLM;
    private DefaultListModel<String> endDLM;
    private DefaultListModel<String> gainDLM;
    private DefaultListModel<String> percentDLM;
    private DefaultListModel<String> dateDLM;
    private DefaultListModel<String> speedDLM;
    
    /**
     * Creates new form Account
     */
    public AccountPanel() {
        
        initComponents();
        
        this.account = new AccountDetails();
        this.tradeHistory = new TradeHistory();
        
        this.startDLM = new DefaultListModel<String>();
        this.endDLM = new DefaultListModel<String>();
        this.gainDLM = new DefaultListModel<String>();
        this.percentDLM = new DefaultListModel<String>();
        this.dateDLM = new DefaultListModel<String>();
        this.speedDLM = new DefaultListModel<String>();
        
        updateAccountUI();
    }
    
    public void updateAccountUI(){
        if(this.account != null)
        {
            String temp = String.format("%.5f", this.account.getBalance());
            this.value.setText(temp + " BTC");
           
            this.dateJList.setModel(this.dateDLM); 
            this.startJList.setModel(this.startDLM);
            this.endJList.setModel(this.endDLM);
            this.gainJList.setModel(this.gainDLM);
            this.percentJList.setModel(this.percentDLM);
            this.speedJList.setModel(this.speedDLM);
            
            String win = String.format("%.3f", this.tradeHistory.getWinRate());
            this.winRate.setText(win + "%");

            String avg = String.format("%.5f", this.tradeHistory.getAvgTrade());
            this.avgTrade.setText(avg + " BTC");
            
            String lot = String.valueOf(this.account.getLot());
            lotLbl.setText(lot);
            
            repaint();
        }
    }
    
    public void newTrade(Trade newTrade){
        String start = String.format("%.5f", newTrade.getStart());
        this.startDLM.addElement(start);
        
        String end = String.format("%.5f", newTrade.getFinal());
        this.endDLM.addElement(end); 
        
        String gain = String.format("%.5f", newTrade.getGain());
        this.gainDLM.addElement(gain); 
        
        String percent = String.format("%.5f", newTrade.getPercent());
        this.percentDLM.addElement(percent + "%"); 
        
        LocalDateTime date = newTrade.getDate();
        String tradeDate = date.format(DateTimeFormatter.ofPattern("dd-MMM-yy"));
        this.dateDLM.addElement(tradeDate); 
        
        System.out.println(newTrade.getSpeed());
        String executionSpeed = String.format("%.2f", newTrade.getSpeed());
        this.speedDLM.addElement(executionSpeed + " ms"); 
    }
    
    public void resetAccount(){
        this.dateDLM.clear();
        this.startDLM.clear();
        this.endDLM.clear();
        this.gainDLM.clear();
        this.percentDLM.clear();
        this.speedDLM.clear();
        
        this.tradeHistory.resetAccount();
        
        this.account.resetBalance();
        
        updateAccountUI();
    }
    
    private void dummyTrade(){
//        String start = JOptionPane.showInputDialog(this, "Enter Start Amount", "Dummy Trade", 3);
//        float setStart = Float.parseFloat(start);
       
        String end = JOptionPane.showInputDialog(this, "Enter End Amount", "Dummy Trade", 3);
        float setEnd = Float.parseFloat(end);
        
        Trade dummyTrade = new Trade(this.account.getLot(), setEnd, 0); 
        newTrade(dummyTrade); 
        this.tradeHistory.addTrade(dummyTrade); 
        
        this.account.changeBalance(dummyTrade.getGain());
        
        updateAccountUI();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        value = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        endJList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        startJList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        gainJList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        percentJList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        speedJList = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        winRate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        avgTrade = new javax.swing.JLabel();
        resetBtn = new javax.swing.JButton();
        dummyBtn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        dateJList = new javax.swing.JList<>();
        changeLotBtn = new javax.swing.JButton();
        lotLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1043, 547));
        setMinimumSize(new java.awt.Dimension(1043, 547));
        setPreferredSize(new java.awt.Dimension(1043, 547));

        value.setFont(new java.awt.Font("Sitka Banner", 0, 24)); // NOI18N
        value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        value.setText("jLabel1");

        endJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(endJList);

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trade Date");

        startJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(startJList);

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Start Amount");

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("End Amount");

        gainJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(gainJList);

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gain/Loss");

        percentJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(percentJList);

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel5.setText("Percent Gain/Loss");

        speedJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(speedJList);

        jLabel6.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Execution Speed");

        jLabel7.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Win Rate");

        winRate.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        winRate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winRate.setText("jLabel8");

        jLabel8.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Avg. Trade");

        avgTrade.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        avgTrade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgTrade.setText("jLabel8");

        resetBtn.setText("Reset Account");
        resetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetBtnMouseClicked(evt);
            }
        });
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        dummyBtn.setText("Dummy Trade");
        dummyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dummyBtnMouseClicked(evt);
            }
        });
        dummyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dummyBtnActionPerformed(evt);
            }
        });

        dateJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(dateJList);

        changeLotBtn.setText("Change Lot");
        changeLotBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeLotBtnMouseClicked(evt);
            }
        });
        changeLotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLotBtnActionPerformed(evt);
            }
        });

        lotLbl.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        lotLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lotLbl.setText("0");

        jLabel10.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Lot: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lotLbl)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(value, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addGap(143, 143, 143))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel5)
                                    .addGap(16, 16, 16)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resetBtn)
                        .addGap(18, 18, 18)
                        .addComponent(dummyBtn)
                        .addGap(18, 18, 18)
                        .addComponent(changeLotBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(winRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(avgTrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lotLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(winRate, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avgTrade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 117, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetBtn)
                            .addComponent(dummyBtn)
                            .addComponent(changeLotBtn))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetBtnMouseClicked
        
    }//GEN-LAST:event_resetBtnMouseClicked

    private void dummyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dummyBtnMouseClicked
        
    }//GEN-LAST:event_dummyBtnMouseClicked

    private void dummyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dummyBtnActionPerformed
        dummyTrade();
    }//GEN-LAST:event_dummyBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        resetAccount();
    }//GEN-LAST:event_resetBtnActionPerformed

    private void changeLotBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeLotBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_changeLotBtnMouseClicked

    private void changeLotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLotBtnActionPerformed
        // Prompt user for new lot allocation
        String lot = JOptionPane.showInputDialog(this, "Enter Desired Lot Amount", "Set Lot", 3);
        float setLot = Float.parseFloat(lot);
        
        
        this.account.changeLot(setLot);
    }//GEN-LAST:event_changeLotBtnActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgTrade;
    private javax.swing.JButton changeLotBtn;
    private javax.swing.JList<String> dateJList;
    private javax.swing.JButton dummyBtn;
    private javax.swing.JList<String> endJList;
    private javax.swing.JList<String> gainJList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lotLbl;
    private javax.swing.JList<String> percentJList;
    private javax.swing.JButton resetBtn;
    private javax.swing.JList<String> speedJList;
    private javax.swing.JList<String> startJList;
    private javax.swing.JLabel value;
    private javax.swing.JLabel winRate;
    // End of variables declaration//GEN-END:variables
}