/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.Prices;
import Data.Conversions;

/**
 *
 * @author Owner
 */
 public class TrianglePanel extends javax.swing.JPanel {

    private static Prices prices; 
    private static Conversions conversions;
    
    /**
    * Creates new form Triangle
    */

    public TrianglePanel() {
        this.prices = new Prices();
        this.conversions = new Conversions(); 
        
        initComponents();
        
    }
    
    public void updateTriangleUI(){
        if(this.prices != null)
        {
            ///////////////////////////     UPDATE CONVERSION RATES     ///////////////////////////
            this.prices.updatePrices();

            String rate1 = String.format("%.5f", this.prices.getBTCLTCRate());
            this.btcltcRateLbl.setText(rate1);

            String rate2 = String.format("%.5f", this.prices.getLTCETHRate());
            this.ltcethRateLbl.setText(rate2);
            
            String rate3 = String.format("%.5f", this.prices.getETHBTCRate());
            this.ethbtcRateLbl.setText(rate3); 
            
            ///////////////////////////     UPDATE COIN AMOUNTS     ///////////////////////////
            this.conversions.updateAmts();

            String btcStart = String.format("%.5f", this.conversions.getbtcStart());
            this.btcAmtStart.setText(btcStart);

            String ltcAmt = String.format("%.5f", this.conversions.getltcAmt());
            this.ltcAmt.setText(ltcAmt);

            String ethAmt = String.format("%.5f", this.conversions.getethAmt());
            this.ethAmt.setText(ethAmt);

            String btcFinal = String.format("%.5f", this.conversions.getbtcFinal());
            this.btcAmtFinal.setText(btcFinal); 
        }
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeBackground = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        ltcLbl = new javax.swing.JLabel();
        btcLbl = new javax.swing.JLabel();
        ethLbl = new javax.swing.JLabel();
        btcltcRateLbl = new javax.swing.JLabel();
        ltcethRateLbl = new javax.swing.JLabel();
        ethbtcRateLbl = new javax.swing.JLabel();
        btcAmtStart = new javax.swing.JLabel();
        ethAmt = new javax.swing.JLabel();
        ltcAmt = new javax.swing.JLabel();
        btcAmtFinal = new javax.swing.JLabel();
        titleLbl.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        titleLbl.setText("Bitcoin Triangular Arbitrage Bot");

        ltcLbl.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        ltcLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltcLbl.setText("LTC");

        btcLbl.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        btcLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btcLbl.setText("BTC");

        ethLbl.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        ethLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ethLbl.setText("ETH");

        btcltcRateLbl.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btcltcRateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btcltcRateLbl.setText("");

        ltcethRateLbl.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        ltcethRateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltcethRateLbl.setText("");

        ethbtcRateLbl.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        ethbtcRateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ethbtcRateLbl.setText("");

        btcAmtStart.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btcAmtStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btcAmtStart.setText("");

        ethAmt.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        ethAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ethAmt.setText("");

        ltcAmt.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        ltcAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltcAmt.setText("");

        btcAmtFinal.setFont(new java.awt.Font("Sitka Text", 0, 12)); // NOI18N
        btcAmtFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btcAmtFinal.setText("");

        javax.swing.GroupLayout homeBackgroundLayout = new javax.swing.GroupLayout(homeBackground);
        homeBackground.setLayout(homeBackgroundLayout);
        homeBackgroundLayout.setHorizontalGroup(
            homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ethbtcRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(btcltcRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(homeBackgroundLayout.createSequentialGroup()
                .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeBackgroundLayout.createSequentialGroup()
                    .addGap(363, 363, 363)
                        .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homeBackgroundLayout.createSequentialGroup()
                                .addComponent(btcAmtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btcLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btcAmtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(homeBackgroundLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(ethAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ethLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(ltcethRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(ltcLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ltcAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(177, Short.MAX_VALUE))
        );
        homeBackgroundLayout.setVerticalGroup(
            homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btcLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcAmtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btcAmtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcltcRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ethbtcRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeBackgroundLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltcLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ethLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ltcethRateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeBackgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(homeBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltcAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ethAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))))
        );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(homeBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btcAmtFinal;
    private javax.swing.JLabel btcAmtStart;
    private javax.swing.JLabel btcLbl;
    private javax.swing.JLabel btcltcRateLbl;
    private javax.swing.JLabel ethAmt;
    private javax.swing.JLabel ethLbl;
    private javax.swing.JLabel ethbtcRateLbl;
    private javax.swing.JPanel homeBackground;
    private javax.swing.JLabel ltcAmt;
    private javax.swing.JLabel ltcLbl;
    private javax.swing.JLabel ltcethRateLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
