/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.*;
import java.util.ArrayList; 
import javax.swing.DefaultListModel;

import net.jacobpeterson.alpaca.AlpacaAPI;
import net.jacobpeterson.alpaca.model.endpoint.account.Account;
import net.jacobpeterson.alpaca.model.endpoint.order.Order;
import net.jacobpeterson.alpaca.model.endpoint.order.enums.OrderSide;
import net.jacobpeterson.alpaca.model.endpoint.order.enums.OrderTimeInForce;
import net.jacobpeterson.alpaca.model.endpoint.position.Position;
import net.jacobpeterson.alpaca.rest.AlpacaClientException;

/**
 *
 * @author Owner
 */
public class Home extends javax.swing.JFrame {
    
    public static Account account;
    public static AlpacaAPI alpacaAPI;

    public static Home self;
    
    private List<Position> positions; 
    private DefaultListModel positionList;
    
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        
        this.self = this;
        
        this.positions = new ArrayList<Position>();
        this.positionList = new DefaultListModel();
        
        /////////////////////////////////////////////////////////////           CREATES ACCOUNT ENDPOINT            /////////////////////////////////////////////////////////////  
        
        this.alpacaAPI = new AlpacaAPI();
        
        try {
            // Get 'Account' information and print it out
            this.account = this.alpacaAPI.account().get();
            System.out.println(this.account);
        } catch (AlpacaClientException exception) {
            exception.printStackTrace();
        }
        
        updateUI();
        
    }
    
    private void updateUI(){
        
        try{
            this.positions = this.alpacaAPI.positions().get();
        } catch (AlpacaClientException exception) {
            exception.printStackTrace();
        }
        
        this.positionList.clear();
        
        for(Position openPosition : this.positions){
            this.positionList.addElement(openPosition.getSymbol());
        }
        
        jList1.setModel(this.positionList); 
        
        this.jLabel1.setText(this.account.getPortfolioValue());
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        buyBTN = new javax.swing.JToggleButton();
        sellBTN = new javax.swing.JToggleButton();
        refreshBTN = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setText("Positions");

        buyBTN.setText("Buy AAPL");
        buyBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBTNMouseClicked(evt);
            }
        });

        sellBTN.setText("Sell AAPL");
        sellBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellBTNMouseClicked(evt);
            }
        });

        refreshBTN.setText("Refresh");
        refreshBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refreshBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sellBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sellBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buyBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBTNMouseClicked
        try {
            Order aaplLimitOrder = this.alpacaAPI.orders().requestMarketOrder("AAPL", 1, OrderSide.BUY, OrderTimeInForce.DAY);
                    
            System.out.printf("Requested %s %s order at %s\n",
                    aaplLimitOrder.getSymbol(),
                    aaplLimitOrder.getType(),
                    aaplLimitOrder.getSubmittedAt());      
        } catch (AlpacaClientException exception) {
            exception.printStackTrace();
        }
        
        updateUI();
    }//GEN-LAST:event_buyBTNMouseClicked

    private void sellBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBTNMouseClicked
        try {
            Order aaplLimitOrder = Home.alpacaAPI.orders().requestMarketOrder("AAPL", 1, OrderSide.SELL, OrderTimeInForce.DAY);
                    
            System.out.printf("Requested %s %s order at %s\n",
                    aaplLimitOrder.getSymbol(),
                    aaplLimitOrder.getType(),
                    aaplLimitOrder.getSubmittedAt());
        } catch (AlpacaClientException exception) {
            exception.printStackTrace();
        }
        
        updateUI();
    }//GEN-LAST:event_sellBTNMouseClicked

    private void refreshBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBTNMouseClicked
        updateUI();
    }//GEN-LAST:event_refreshBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buyBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton refreshBTN;
    private javax.swing.JToggleButton sellBTN;
    // End of variables declaration//GEN-END:variables
}
